site_name: Token Counter Docs

theme:
  name: "material"
  features:
    - navigation.tabs
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

nav:
  - Index: index.md
  - Tutorial: tutorials.md
  - Reference: reference.md
